### ISSUE TITLE
Server preparation

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#1]
## Value statement
As a **developer** 
I need **a server** 
so that **my database is not exposed in the frontend** 

## Description
I need a NodeJS server acting as an intermediary between my frontend and the MondoDB database to avoid exposing user data.

## Acceptance criteria
- [ ] I can send a request to my server and get a JSON response. 

## Tasks
- [ ] install Express, dotenv, nodemon
- [ ] Setup simple server

## Size
small

**Comment by Kheirah** [comment]
Clear and concise, very good 😃 

Do you plan on setting up your own backend system (and if so, where are you going to deploy it? just curious 😄) or are you going to use vercel serverless functions to communicate with the MongoDB?

**Comment by VladF146** [comment]
Thank you. I will deploy my express server on netlify or heroku :)
