### ISSUE TITLE
Core Application Pages and Navigation

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#10]
## Value statement
As a **user** 
I need **clear navigation and page structure** 
so that **I can jump between unrelated tasks** 

## Description
After login the user is presented with a different layout: Header, Content area, navbar - from top to bottom.
When clicking on the navbar links, different pages are rendered.
The new routes are protected as well.

## Acceptance criteria
- [ ] a different layout is presented after signup/signin
- [ ] navbar can be used to navigate between pages
- [ ] pages can't be reached without authentication

## Tasks
- [ ] create home, edit and settings pages
- [ ] put them in a mutual layout
- [ ] create a functioning navbar component, that lets you jump between pages
- [ ] test if new routes are protected

## Size
medium

**Comment by Kheirah** [comment]
To start with the navigation often is the first reaction of a developer, but it's actually of little value to the user when all they can do is to navigate between empty pages.

You can go ahead and implement the navigation, but be aware that a more valuable user story would be one which provides actual value in the sense of functionality, something like a core feature which allows the user to interact with it. And as feature after feature are being added, you eventually build out the navigation between elements that already have intrinsic value.

I just wanted to mention that. Now you may go ahead and code up the navbar =)
