### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#11]
## Value statement
As a **user** 
I need **a home page** 
so that **I get to see all the notes I created**

## Description
After signing in the user lands on the home page, where all of his/her notes are loaded.

## Acceptance criteria
- [ ] data is loaded automatically
- [ ] only the users data is loaded

## Tasks
- [ ] Create a Home page
- [ ] Create a global state and fill it with fetched data
- [ ] Show the data on the home page

## Size
small
