### ISSUE TITLE
Details Page

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#12]
## Value statement
As a **user** 
I need **a details page** 
so that **I can view every note separately** 

## Description
On the home page the user can click on a specific note a be redirected to a page with only these notes information.

## Acceptance criteria
- [ ] When a note is clicked on, the user is redirected to a details page of the same note

## Tasks
- [ ] create a details page
- [ ] Make it load data based on the url parameter

## Size
small
