### ISSUE TITLE
Edit mode

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#13]
## Value statement - a requirement, not a solution
As a **user** 
I need **an edit mode** 
so that **I can edit the content of a single note** 

## Description
When viewing a single note, the user has the option to toggle between view and toggle mode. After selecting the edit mode, the user can change the title and content of the note.

## Acceptance criteria
- [ ] user can change the content of the note
- [ ] The new content is saved

## Tasks
- [ ] create a Toggle
- [ ] make the content editable on toggle
- [ ] Update the database and global state

## Size
small
