### ISSUE TITLE
Create New Note page

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#14]
## Value statement
As a **user** 
I need **a note creation page** 
so that **I can actually create notes** 

## Description
When visiting the page, a form can be filled out and submitted to create a new note.

## Acceptance criteria
- [ ] note can only be created, when all fields are filled out
- [ ] After the note is created, it is saved to db

## Tasks
- [ ] create a new note page with a form
- [ ] Save it to db and global state
- [ ] Prove creation by loading it from db in home page

## Size
medium
