### ISSUE TITLE
Update and Delete Note functionality

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#15]
## Value statement
As a **user** 
I need **the update/delete functionalities** 
so that **I can modify my notes after they are created** 

## Description (Text, Scribble, Wireframe, Design)
Self explanatory

## Acceptance criteria
- [ ] When an existing card is updated, the update is saved to the database; the user is redirected to /notes, where he can view the updated note
- [ ] When  an existing card is deleted, it can't be loaded from the database anymore; the user is redirected to /notes

## Tasks
- [ ] Create the update & delete buttons
- [ ] Modify notes context and db on click.

## Size
small
