### ISSUE TITLE
Refactoring styling and fetching logic

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#16]
## Value statement
As a **developer** 
I need **to refactor my code** 
so that **complexity is reduced and code understanding is improved** 

## Description
React Components are cleaned up by outsourcing the styling and fetching logic to separate files

## Acceptance criteria
- [ ] less cluttered react components
- [ ] better overall file structure inside the code base

## Tasks
- [ ] move styling logic to separate files (component.styles.js)
- [ ] install axios and react query
- [ ] move fetching logic to services
- [ ] handle the fetching services with react query

## Size
medium
