### ISSUE TITLE
UI/UX Improvements

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#17]
## Value statement
As a **user** 
I need **a good UI/UX** 
so that **I can enjoy the application even more** 

## Acceptance criteria
- [ ] better UI (uniform styling; no styling breaks)
- [ ] better UX (show password functionality; no redundant components)

## Tasks
- [ ] Remove the header
- [ ] Improve overall styling of the app
- [ ] Add a show password functionality to the signin/up forms

## Size
small
