### ISSUE TITLE
Component testing

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#18]
## Value statement
As a **developer** 
I need **component testing** 
so that **I can find and solve defects in my code thereby lowering risks** 

## Description
Tests will be created based on component complexity;
Toggle => few test cases;
PasswordInput => right in between;
Authentication Page => many tests;

## Acceptance criteria
- [ ] tests cover all imaginable cases of user interaction
- [ ] redundancy inside test code is minimized

## Tasks
- [ ] update @testing-library/user-event
- [ ] make modifications to solve jest errors
- [ ] create the 3 tests
- [ ] cover all cases of user interaction

## Size
large
