### ISSUE TITLE
Refactoring styling and routing

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#19]
## Value statement
As a **developer** 
I need **to refactor my code** 
so that **complexity is reduced and code understanding is improved**

As a **user** 
I need **modern routing and responsivity features** 
so that **my user experience is not impaired**

## Description
Routing is cleaned up; Better responsivity on big screens.

## Acceptance criteria
- [ ] less cluttered Routing code
- [ ] better overall file structure inside the code base
- [ ] Overall better UX - after signin user is redirected back to where he came from

## Tasks
- [ ] refactor route protection
- [ ] add 404 page
- [ ] make styling mode responsive on bigger screens

## Size
medium

**Comment by Kheirah** [comment]
Optimizing code is the bread and butter of development, I'm with you there. But try seeing these improvements from the **perspective of a user.** Articulate the value your improvement is going to have such that the user benefits from it.
