### ISSUE TITLE
Routes for Tutorial Api

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#2]
## Value statement
As a **developer** 
I need **to create API routes** 
so that **I can access different functionalities via url** 

## Description
I need a router, so I can map CRUD operations to different urls 

## Acceptance criteria 
- [ ] I can send requests to different API URLs and get a route/method specific response.

## Tasks
- [ ] Create a routers directory
- [ ] Create a router file for tutorial operations (get all, get single, post single, update single, delete single)
- [ ] Create a controllers directory
- [ ] Abstract away the callbacks from the router into a separate tutorial controller file

## Size
small

**Comment by Kheirah** [comment]
If not already done, include a catch-all route in case the user inputs a route that doesn't exist 😄

**Comment by VladF146** [comment]
Saw too late. Martin made me pay for it 😆
