### ISSUE TITLE
Better A11y and UX

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#20]
## Value statement
As a **user** 
I need **better routing and accessibility features** 
so that **my user experience is not impaired**

## Description
Signout whenever the authentication token is expired. Path is remembered to come back, after signin.
Inputs get a green otline to indicate focus state.

## Acceptance criteria
- [ ] Signout when JWT is expired (401 Error)
- [ ] Green border on inputs when typing

## Tasks
- [ ] Add input otline on focus (focus-within)
- [ ] dispatch SIGNOUT whener 401 Error comes back from API (JWT problems)

## Size
small
