### ISSUE TITLE
Note deletion Modal

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#21]
## Value statement
As a **user** 
I need **a modal after (accidentally) clicking on the delete button** 
so that **I can reconsider my decision** 

## Description
After clicking on the Delete button, the user is presented with a modal, where he can approve or abort his decision.

## Acceptance criteria
- [ ] Open modal when clicking on Delete button
- [ ] Close modal when clicking on backdrop, Close button or the Cancel button
- [ ] Delete note and redirect to /notes when clicking on Approve

## Tasks
- [ ] Create a modal component
- [ ] Create a backdrop that blurs the background
- [ ] Create a modal with an information text and the approve, abort buttons
- [ ] Delete button opens the modal
- [ ] pass the handleDelete function to the Approve button

## Size
small
