### ISSUE TITLE
Connecting to the database

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#3]
## Value Statement
As a **developer** 
I need **a database** 
so that **user data can persist** 

## Description
Combining mongoose schemas and the Rest API i can communicate with the database in a structured and predictable manner.

## Acceptance criteria
- [ ] When making API request, data should be saved and updated to, retrieved and deleted from MongoDB based on request method and body.

## Tasks
- [ ] install mongoose
- [ ] Connect to mongodb and start server after successful connection
- [ ] Create a models directory
- [ ] Create a file with a basic Schema for the tutorials
- [ ] Modify the controller file, so that data is saved and modified inside database based on API request

## Size
medium

**Comment by Kheirah** [comment]
LGTM!
