### ISSUE TITLE
Authentication API

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#4]
## Value statement
As a **developer** 
I need **a dedicated API for authentication** 
so that **authentication and (later) authorization can both be handled in a structured way** 

## Description
In the same way as the Tutorials API, I would like to create an Authentication API.
For this I will split the system into router/controller/model.
The actual logic and distinction between signin and signup will be handled in the next user story.

## Acceptance criteria
- [x] When making a request to the API (.../api/users/signin; .../api/users/signin) a JSON object with a message will be received.

## Tasks
- [x] Create a router directory and file for users
- [x] Create a controllers directory and file for users
- [x] Create a model directory and file for users
- [x] Use the new router

## Size
small
