### ISSUE TITLE
Sign up user

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#5]
## Value statement
As a **developer** 
I need **an encryption mechanism during the signup process** 
so that **user data stays safe even if database is compromised**

## Description
Email and password are send to the server. Before being send to database, data is validated, the password is encrypted.

## Acceptance criteria
- [ ] During signup user data is validated for completeness, strength, conflict
- [ ] Password is saved in encrypted version
- [ ] User is saved and sent back; email untouched, password hashed

## Tasks
- [ ] install bcrypt
- [ ] install validator
- [ ] validate user input
- [ ] hash password before saving to db 

## Size
medium
