### ISSUE TITLE
Signin user

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#6]
## Value statement
As a **developer** 
I need **an mechanism to verify whether someone is signed in** 
so that **I can protect routes and show content only relevant to the user**

## Description
Email and password are send to the server. Before being send to database, data is validated, the password is encrypted.

## Acceptance criteria
- [ ] During signin user data is validated
- [ ] Password is compared to hashed password from db
- [ ] a token is generated based on user.id and a "secret", in production known only to the developer
- [ ] User email and the jwtoken are sent back

## Tasks
- [ ] modify the signin controller, such that it validates user data
- [ ] check for existance of user
- [ ] check for correctness of password with bcrypt.compare()
- [ ] send back email & token

## Size
medium
