### ISSUE TITLE
Protect routes

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#7]
## Value statement
As a **developer** 
I need **a mechanism to protect specific routes** 
so that **a user can only access information when signed in and the information belongs to the user** 

## Description
The access token send to the user during signin/signup is used to check for users identity when making a request. The id is saved with the data posted by the user. The data requested is checked for ownership by the user by comparing the userIds.

## Acceptance criteria
- [ ] Middleware checks for existance of jwtoken to controll whether user is signed in
- [ ] When making request, the jwtoken is decrypted and the user id is accessed and saved inside the request object
- [ ] When accessing Tutorials API the the user id is used to access only the user relevant data from the database

## Tasks
- [ ] Create middleware to check for authentication status (existance of jwt)
- [ ] saved id from middleware to req object
- [ ] use middleware inside Tutorials API
- [ ] make the tutorials controllers compare the user id from request object to user id saved in the database
- [ ] send only user corresponding data

## Size
medium
