### ISSUE TITLE
Signup process in the frontend

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#8]
## Value statement
As a **user**
I need a **signup mechanism** 
so that **my data can be connected to me and is protected from other users** 

## Description
When visiting the site, the user is navigated to the signup page, when not authenticated yet.
After signup the user is navigated to the home page; His email is shown, to verify his identity. A logout button is presented. After clicking on it, the user is redirected to the signup page again.
Whenever validation or mongoDB errors are thrown by the backend, they are shown to the user too.

<p float="left">
<img src="https://user-images.githubusercontent.com/91379399/199250683-30c63a32-9704-4d90-add3-fbdaacb42561.png" alt="Before Signup" width="300">
<img src="https://user-images.githubusercontent.com/91379399/199250816-6581b0cb-b057-48d8-bfad-c62e68241f93.png" alt="After Signup" width="300">
</p>

## Acceptance criteria
- [ ] All routes are protected, except /signup, if not signedup
- [ ] Errors are shown under the signup button
- [ ] After successful signup, user is stored in local storage and redirected to home page
- [ ] User can logout; if he does, he will be redirected to the signup page again

## Tasks
- [ ] create a react app
- [ ] clean it up, install eslint
- [ ] install react-router, styled-components
- [ ] create an authentication context and make it available for the whole app
- [ ] react to errors and make repeated requests impossible with an loading state
- [ ] save user to local storage, get him on page reload
- [ ] protect some routes based on existance of user
- [ ] create an signout mechanism for better testing

## Size
large

**Comment by philmetscher** [comment]
I think your **Value statement** markup is not correct rn 😅 

`After signup the user is navigated to the home page; His email is shown, to verify his identity. `
What do you mean by `His email is shown, to verify his identity`. Maybe you could describe it a little bit more. (Pictures help)

I also think thats a very big user-story. Maybe you can split it up

**Comment by VladF146** [comment]
@philmetscher
Hey Phil, thank you for your review. The story is big, yes, but I think this is what **"Size: large"** is for 👍

The funny thing is, I split it up already, since the **Signin** functioanlity would be overkill. What I am creating right now is the frontend for the REST API I created last week. Unfortunately it's quit difficult to test the backend without a corresponding client side.

Added the images; as you can see the second screen is there to test the signup functionality in the first screen.
