### ISSUE TITLE
Signin process in the frontend

### ISSUE THREAD

**Issue by VladF146** [VladF146/capstone-prephase#9]
## Value statement
As a **user**
I need a **signin mechanism** 
so that **my data can be connected to me and is protected from other users** 

## Description
Same as this user story, only difference is, the account has to be already created.
[Signup process in the frontend](https://github.com/VladF146/capstone-prephase/issues/8)

## Acceptance criteria
- [ ] All routes are protected, except /signup and /signin, if not signed up or signed in
- [ ] Errors are shown under the signup button
- [ ] After successful signup/ signin, user is stored in local storage and redirected to home page
- [ ] User can logout; if he does, he will be redirected to the signin page

## Tasks
- [ ] create an additional page for signin
- [ ] connect the signup and signin pages with a link, so the user can navigate between them

## Size
small

**Comment by marcbendixen** [comment]
Looks good to me 👍
